# -*- coding: utf-8 -*-
"""Ragpipeline2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n8qzqAueCO43itfFPnm1DfBX9WnfGTFC
"""

import pandas as pd, os
from google.colab import drive
drive.mount('/content/drive')
D = '/content/drive/MyDrive/graphrag_research/'

print("--- files on Drive ---")
for f in sorted(os.listdir(D)):
    print(' ', f)

if os.path.exists(D + 'baseline_medqa_matched.csv'):
    df = pd.read_csv(D + 'baseline_medqa_matched.csv')
    print(f"\nmatched baseline: {len(df)}/1273 done, {df['is_correct'].mean()*100:.1f}% so far")

!pip install anthropic datasets statsmodels -q
import anthropic, pandas as pd, numpy as np, os, time, shutil
from datasets import load_dataset
from google.colab import drive
from statsmodels.stats.contingency_tables import mcnemar
from statsmodels.stats.proportion import proportion_confint

drive.mount('/content/drive', force_remount=False)
D = '/content/drive/MyDrive/graphrag_research/'

ANTHROPIC_API_KEY = "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"
client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
# add the workspace header back if you needed it:
# client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY,
#     default_headers={"anthropic-workspace-id": "wrkspc_..."})

test  = load_dataset("GBaker/MedQA-USMLE-4-options")['test']
total = len(test)

def ask(q, opts_d, retries=5):
    opts = "\n".join(f"{k}: {v}" for k, v in opts_d.items())
    prompt = (f"You are a medical expert. Answer this clinical question.\n\n"
              f"Question: {q}\n\n{opts}\n\nReply with only the letter A, B, C, or D. Nothing else.")
    for a in range(retries):
        try:
            r = client.messages.create(model="claude-opus-5", max_tokens=2000,
                                       messages=[{"role":"user","content":prompt}])
            for b in r.content:
                if b.type == "text":
                    for ch in b.text.strip():
                        if ch in "ABCD": return ch
            return "X"
        except Exception as e:
            print(f"  {e}"); time.sleep(60 if '529' in str(e) else 10)
    return "X"

L, R = 'baseline_medqa_matched.csv', D + 'baseline_medqa_matched.csv'
shutil.copy(R, L)
rows  = pd.read_csv(L).to_dict('records')
start = len(rows)
print(f"resuming at {start+1}/{total}")

for i in range(start, total):
    it = test[i]
    p  = ask(it['question'], it['options'])
    rows.append({'idx': i, 'predicted': p, 'correct': it['answer_idx'],
                 'is_correct': p == it['answer_idx']})
    if (i+1) % 10 == 0:
        pd.DataFrame(rows).to_csv(L, index=False); shutil.copy(L, R)
    print(f"{i+1}/{total} | {p} vs {it['answer_idx']} | {sum(r['is_correct'] for r in rows)/len(rows)*100:.1f}%")
    time.sleep(0.5)

pd.DataFrame(rows).to_csv(L, index=False); shutil.copy(L, R)
base = pd.DataFrame(rows)['is_correct'].astype(bool).values
n = len(base)
lo, hi = proportion_confint(base.sum(), n, 0.05, method='wilson')
print(f"\n=== MATCHED BASELINE: {base.mean()*100:.1f}%  [{lo*100:.1f}%, {hi*100:.1f}%] ===\n")

for name, f in [('Flat-Vector RAG','rag_opus5_results.csv'),
                ('Static GraphRAG','graphrag_opus5_results.csv'),
                ('Hybrid GraphRAG','hybrid_graphrag_results.csv')]:
    v = pd.read_csv(D+f)['is_correct'].astype(bool).values
    m = min(n, len(v)); a, b_ = base[:m], v[:m]
    x, y = int(np.sum(a & ~b_)), int(np.sum(~a & b_))
    p = mcnemar([[0,x],[y,0]], exact=(x+y)<25, correction=(x+y)>=25).pvalue
    print(f'{name:<18} {v.mean()*100:.1f}%  b={x:<4} c={y:<4} p={p:.4f}  {"SIG" if p<0.05 else "n.s."}')



# Commented out IPython magic to ensure Python compatibility.
import os
from google.colab import drive

drive.mount('/content/drive')
BASE = '/content/drive/MyDrive/graphrag_clinical/'
os.makedirs(BASE, exist_ok=True)
# %cd {BASE}

# MIMIC-IV Clinical Database Demo v2.2 — open access, ~100 patients
!wget -q -r -N -c -np --show-progress \
    https://physionet.org/files/mimic-iv-demo/2.2/

print("done")

import pandas as pd

ROOT = BASE + 'physionet.org/files/mimic-iv-demo/2.2/'

pat = pd.read_csv(ROOT + 'hosp/patients.csv.gz')
adm = pd.read_csv(ROOT + 'hosp/admissions.csv.gz')

counts = adm.groupby('subject_id').size().sort_values(ascending=False)

print(f"patients        : {len(pat)}")
print(f"admissions      : {len(adm)}")
print(f"2+ admissions   : {(counts >= 2).sum()}")
print(f"3+ admissions   : {(counts >= 3).sum()}")
print(f"\ntop 12 by admission count:")
print(counts.head(12).to_string())

for name in ['diagnoses_icd', 'procedures_icd', 'labevents', 'prescriptions']:
    df = pd.read_csv(ROOT + f'hosp/{name}.csv.gz')
    print(f"{name:<16} {len(df):>8,} rows   "
          f"{len(df)/df.subject_id.nunique():>7.0f} per patient")

import pandas as pd

dx  = pd.read_csv(ROOT + 'hosp/diagnoses_icd.csv.gz')
dic = pd.read_csv(ROOT + 'hosp/d_icd_diagnoses.csv.gz')

single = counts[counts == 1].index.tolist()[:4]      # baseline retrieval
multi  = counts[counts >= 3].index.tolist()[:6]      # longitudinal reasoning
COHORT = single + multi

titles = dict(zip(dic.icd_code, dic.long_title))
for sid in COHORT:
    top = dx[dx.subject_id == sid].sort_values('seq_num').head(2)
    focus = "; ".join(titles.get(c, c)[:45] for c in top.icd_code)
    print(f"{sid}  {counts[sid]:>2} adm   {focus}")

!pip install neo4j
from getpass import getpass
from neo4j import GraphDatabase

URI = "neo4j+s://c46c5d64.databases.neo4j.io"
PWD = getpass("Password: ").strip()

for user in ["neo4j", "c46c5d64"]:
    try:
        d = GraphDatabase.driver(URI, auth=(user, PWD))
        d.verify_connectivity()
        print(f"✓ works with username: {user}")
        driver = d
        break
    except Exception as e:
        print(f"✗ {user}: {type(e).__name__}")

import pandas as pd

n = cypher("MATCH (l:LabEvent) RETURN count(l) AS n")[0]["n"]
assert n == 0, f"{n:,} LabEvent nodes already exist — delete them before reloading."

DB   = "c46c5d64"
ROOT = BASE + 'physionet.org/files/mimic-iv-demo/2.2/'
def load(t): return pd.read_csv(ROOT + f'hosp/{t}.csv.gz')

pat  = load('patients');       adm  = load('admissions')
dx   = load('diagnoses_icd');  ddx  = load('d_icd_diagnoses')
proc = load('procedures_icd'); dpr  = load('d_icd_procedures')
rx   = load('prescriptions');  lab  = load('labevents')
dlab = load('d_labitems')

def run(q, rows=None, batch=500):
    with driver.session(database=DB) as s:
        if rows is None:
            s.run(q); return
        for i in range(0, len(rows), batch):
            s.run(q, rows=rows[i:i+batch])

for c in [
  "CREATE CONSTRAINT IF NOT EXISTS FOR (p:Patient)    REQUIRE p.subject_id IS UNIQUE",
  "CREATE CONSTRAINT IF NOT EXISTS FOR (a:Admission)  REQUIRE a.hadm_id    IS UNIQUE",
  "CREATE CONSTRAINT IF NOT EXISTS FOR (d:Diagnosis)  REQUIRE d.icd_code   IS UNIQUE",
  "CREATE CONSTRAINT IF NOT EXISTS FOR (p:Procedure)  REQUIRE p.icd_code   IS UNIQUE",
  "CREATE CONSTRAINT IF NOT EXISTS FOR (m:Medication) REQUIRE m.name       IS UNIQUE",
  "CREATE INDEX IF NOT EXISTS FOR (l:LabEvent) ON (l.label)",
]: run(c)

run("""UNWIND $rows AS r
MERGE (p:Patient {subject_id: r.subject_id})
SET p.gender=r.gender, p.anchor_age=r.anchor_age, p.anchor_year=r.anchor_year""",
    pat.to_dict('records'))
print("patients loaded")

run("""UNWIND $rows AS r
MATCH (p:Patient {subject_id: r.subject_id})
MERGE (a:Admission {hadm_id: r.hadm_id})
SET a.admission_type=r.admission_type, a.admittime=r.admittime,
    a.dischtime=r.dischtime, a.discharge_location=r.discharge_location
MERGE (p)-[:HAS_ADMISSION]->(a)""", adm.to_dict('records'))
print("admissions loaded")

dx2 = dx.merge(ddx, on=['icd_code','icd_version'], how='left')
dx2['long_title'] = dx2.long_title.fillna(dx2.icd_code)
run("""UNWIND $rows AS r
MATCH (a:Admission {hadm_id: r.hadm_id})
MERGE (d:Diagnosis {icd_code: r.icd_code})
SET d.long_title=r.long_title, d.icd_version=r.icd_version
MERGE (a)-[:HAS_DIAGNOSIS {seq_num: r.seq_num}]->(d)""", dx2.to_dict('records'))
print("diagnoses loaded")

pr2 = proc.merge(dpr, on=['icd_code','icd_version'], how='left')
pr2['long_title'] = pr2.long_title.fillna(pr2.icd_code)
run("""UNWIND $rows AS r
MATCH (a:Admission {hadm_id: r.hadm_id})
MERGE (p:Procedure {icd_code: r.icd_code})
SET p.long_title=r.long_title
MERGE (a)-[:HAS_PROCEDURE {chartdate: r.chartdate}]->(p)""", pr2.to_dict('records'))
print("procedures loaded")

rx2 = rx.dropna(subset=['drug','hadm_id']).copy()
rx2['drug'] = rx2.drug.str.lower().str.strip()
rx2 = rx2.astype(object).where(rx2.notna(), None)

run("""UNWIND $rows AS r
MATCH (a:Admission {hadm_id: r.hadm_id})
MERGE (m:Medication {name: r.drug})
MERGE (a)-[h:HAS_MEDICATION]->(m)
SET h.route     = r.route,
    h.dose      = r.dose_val_rx,
    h.unit      = r.dose_unit_rx,
    h.starttime = r.starttime""", rx2.to_dict('records'))
print("medications loaded")

lab2 = lab[lab.flag=='abnormal'].dropna(subset=['hadm_id']).merge(
        dlab[['itemid','label']], on='itemid', how='left')
run("""UNWIND $rows AS r
MATCH (a:Admission {hadm_id: r.hadm_id})
CREATE (l:LabEvent {label:r.label, value:r.value, valuenum:r.valuenum,
                    valueuom:r.valueuom, flag:r.flag, charttime:r.charttime})
MERGE (a)-[:INCLUDES_LAB]->(l)""", lab2.to_dict('records'))
print("labs loaded")

with driver.session(database=DB) as s:
    print(s.run("MATCH (n) RETURN labels(n)[0] AS label, count(*) AS n ORDER BY n DESC").to_df())
    print("relationships:", s.run("MATCH ()-[r]->() RETURN count(r) AS n").single()['n'])

lab2 = lab[lab.flag=='abnormal'].dropna(subset=['hadm_id']).merge(
        dlab[['itemid','label']], on='itemid', how='left')

for col in ['label','value','valuenum','valueuom','flag','charttime']:
    lab2[col] = lab2[col].where(lab2[col].notna(), None)

run("""UNWIND $rows AS r
MATCH (a:Admission {hadm_id: r.hadm_id})
CREATE (l:LabEvent {label:r.label, value:r.value, valuenum:r.valuenum,
                    valueuom:r.valueuom, flag:r.flag, charttime:r.charttime})
MERGE (a)-[:INCLUDES_LAB]->(l)""", lab2.to_dict('records'))
print("labs loaded")

with driver.session(database=DB) as s:
    print(s.run("MATCH (n) RETURN labels(n)[0] AS label, count(*) AS n ORDER BY n DESC").to_df())
    print("relationships:", s.run("MATCH ()-[r]->() RETURN count(r) AS n").single()['n'])

QUERIES = {
 "simple: how many admissions": """
    MATCH (p:Patient {subject_id:$sid})-[:HAS_ADMISSION]->(a)
    RETURN count(a) AS admissions""",

 "simple: demographics": """
    MATCH (p:Patient {subject_id:$sid})
    RETURN p.gender AS gender, p.anchor_age AS age""",

 "medium: medications during sepsis admission": """
    MATCH (p:Patient {subject_id:$sid})-[:HAS_ADMISSION]->(a)
          -[:HAS_DIAGNOSIS]->(d:Diagnosis)
    WHERE toLower(d.long_title) CONTAINS 'sepsis'
    MATCH (a)-[:HAS_MEDICATION]->(m:Medication)
    RETURN a.hadm_id AS admission, d.long_title AS diagnosis,
           collect(DISTINCT m.name)[..15] AS medications""",

 "medium: diagnoses recurring across admissions": """
    MATCH (p:Patient {subject_id:$sid})-[:HAS_ADMISSION]->(a)
          -[:HAS_DIAGNOSIS]->(d:Diagnosis)
    WITH d, count(DISTINCT a) AS n WHERE n > 1
    RETURN d.long_title AS diagnosis, n ORDER BY n DESC LIMIT 10""",

 "medium: abnormal labs over time": """
    MATCH (p:Patient {subject_id:$sid})-[:HAS_ADMISSION]->(a)
          -[:INCLUDES_LAB]->(l:LabEvent)
    WHERE l.label CONTAINS 'Creatinine'
    RETURN a.hadm_id AS admission, l.charttime AS time,
           l.valuenum AS value ORDER BY l.charttime LIMIT 20""",
}

SID = 10014354
with driver.session(database=DB) as s:
    for name, q in QUERIES.items():
        print(f"\n--- {name} ---")
        print(s.run(q, sid=SID).to_df().to_string())

q = """
MATCH (p:Patient {subject_id:$sid})-[:HAS_ADMISSION]->(a)-[:HAS_DIAGNOSIS]->(d:Diagnosis)
WHERE d.long_title IS NOT NULL
RETURN DISTINCT d.long_title AS diagnosis ORDER BY diagnosis LIMIT 40
"""
with driver.session(database=DB) as s:
    print(s.run(q, sid=10014354).to_df().to_string())

q = """
MATCH (p:Patient {subject_id:$sid})-[:HAS_ADMISSION]->(a)-[:INCLUDES_LAB]->(l:LabEvent)
WHERE l.label CONTAINS 'Creatinine'
RETURN DISTINCT a.hadm_id AS admission, l.charttime AS time, l.valuenum AS value
ORDER BY time LIMIT 20
"""
with driver.session(database=DB) as s:
    print(s.run(q, sid=10014354).to_df().to_string())

QUERIES = {
 "medications during an acute kidney failure admission": """
    MATCH (p:Patient {subject_id:$sid})-[:HAS_ADMISSION]->(a)
          -[:HAS_DIAGNOSIS]->(d:Diagnosis)
    WHERE toLower(d.long_title) CONTAINS 'acute kidney failure'
    MATCH (a)-[:HAS_MEDICATION]->(m:Medication)
    RETURN a.hadm_id AS admission, a.admittime AS admitted,
           collect(DISTINCT m.name)[..15] AS medications""",

 "did the leukemia go into remission": """
    MATCH (p:Patient {subject_id:$sid})-[:HAS_ADMISSION]->(a)
          -[:HAS_DIAGNOSIS]->(d:Diagnosis)
    WHERE toLower(d.long_title) CONTAINS 'lymphocytic leukemia'
    RETURN DISTINCT a.admittime AS admitted, d.long_title AS status
    ORDER BY admitted""",

 "creatinine around the acute kidney failure episode": """
    MATCH (p:Patient {subject_id:$sid})-[:HAS_ADMISSION]->(a)
          -[:HAS_DIAGNOSIS]->(d:Diagnosis)
    WHERE toLower(d.long_title) CONTAINS 'acute kidney failure'
    MATCH (a)-[:INCLUDES_LAB]->(l:LabEvent)
    WHERE l.label CONTAINS 'Creatinine'
    RETURN DISTINCT a.hadm_id AS admission, l.charttime AS time,
           l.valuenum AS creatinine ORDER BY time""",
}

SID = 10014354
with driver.session(database=DB) as s:
    for name, q in QUERIES.items():
        print(f"\n--- {name} ---")
        print(s.run(q, sid=SID).to_df().to_string())

!pip install anthropic
import anthropic

ANTHROPIC_API_KEY = "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"     # your key between the quotes
client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

# if your key is identity-linked, you'll need the workspace header too:
# client = anthropic.Anthropic(
#     api_key=ANTHROPIC_API_KEY,
#     default_headers={"anthropic-workspace-id": "wrkspc_..."})

print("ready")

q = """
MATCH (p:Patient {subject_id:$sid})-[:HAS_ADMISSION]->(a)
OPTIONAL MATCH (a)-[:HAS_DIAGNOSIS]->(d:Diagnosis)
  WHERE toLower(d.long_title) CONTAINS 'lymphocytic leukemia'
OPTIONAL MATCH (a)-[:HAS_MEDICATION]->(m:Medication)
  WHERE m.name IN ['venetoclax','prednisone']
OPTIONAL MATCH (a)-[:INCLUDES_LAB]->(l:LabEvent)
  WHERE l.label CONTAINS 'Creatinine'
RETURN a.admittime AS admitted,
       CASE WHEN d.long_title CONTAINS 'in remission' THEN 'remission'
            WHEN d.long_title IS NULL THEN '-' ELSE 'active' END AS cll,
       collect(DISTINCT m.name) AS therapy,
       round(max(l.valuenum),1) AS peak_creatinine
ORDER BY admitted
"""
with driver.session(database=DB) as s:
    print(s.run(q, sid=10014354).to_df().to_string())

SID = 10014354

ask("How many hospital admissions has this patient had?", SID)
print("\n" + "="*70 + "\n")
ask("Which medications were given during admissions where the patient "
    "was diagnosed with acute kidney failure?", SID)
print("\n" + "="*70 + "\n")
ask("Show how the patient's leukemia remission status changed over time, "
    "ordered by admission date.", SID)

##queries using cypher text
##backend pipeling using graph
##querly language that can ask the graph
##ideas for hybriding(executive sumamry taht explains in one page)

##2 week time

## the way i start the graph
## graph backend querying on that graph
## cypher queries that we do

